FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App
COPY Backend ./
RUN dotnet restore
RUN dotnet publish Sanatorium.InventoryService.Api/Sanatorium.InventoryService.Api.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "Sanatorium.InventoryService.Api.dll"]